# Generated by Django 3.2.13 on 2022-11-09 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OMC23Nivel1',
            fields=[
                ('idOmc23N1', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='idOmc23N1')),
                ('codigo', models.CharField(max_length=9, unique=True)),
                ('descriEng', models.CharField(max_length=100)),
                ('descriSpa', models.CharField(max_length=110)),
                ('definicionEng', models.CharField(max_length=200)),
                ('definicionSpa', models.CharField(max_length=150)),
                ('ejemploEng', models.CharField(max_length=300)),
                ('ejemploSpa', models.CharField(max_length=400)),
                ('anioReg', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Omc23Nivel1',
                'db_table': 'Omc23Nivel1',
            },
        ),
        migrations.CreateModel(
            name='OMC23Nivel2',
            fields=[
                ('idOmc23N2', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='idOmc23N2')),
                ('numMat', models.IntegerField(blank=True, null=True)),
                ('codigo', models.CharField(max_length=9, unique=True)),
                ('descriEng', models.CharField(max_length=100)),
                ('descriSpa', models.CharField(max_length=110)),
                ('definicionEng', models.CharField(blank=True, max_length=300, null=True)),
                ('definicionSpa', models.CharField(blank=True, max_length=470, null=True)),
                ('ejemploEng', models.CharField(blank=True, max_length=300, null=True)),
                ('ejemploSpa', models.CharField(blank=True, max_length=400, null=True)),
                ('regFinal', models.BooleanField()),
                ('anioReg', models.IntegerField()),
                ('regUsuario', models.BooleanField(blank=True, null=True)),
                ('fk_Omc23N1', models.ForeignKey(db_column='fk_Omc23N1', on_delete=django.db.models.deletion.CASCADE, to='omniclass23.omc23nivel1', verbose_name='Nivel 1')),
            ],
            options={
                'verbose_name': 'Omc23Nivel2',
                'db_table': 'Omc23Nivel2',
            },
        ),
        migrations.CreateModel(
            name='OMC23Nivel3',
            fields=[
                ('idOmc23N3', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='idOmc23N3')),
                ('numMat', models.IntegerField(blank=True, null=True)),
                ('codigo', models.CharField(max_length=9, unique=True)),
                ('descriEng', models.CharField(max_length=100)),
                ('descriSpa', models.CharField(max_length=110)),
                ('definicionEng', models.CharField(blank=True, max_length=350, null=True)),
                ('definicionSpa', models.CharField(blank=True, max_length=450, null=True)),
                ('ejemploEng', models.CharField(blank=True, max_length=250, null=True)),
                ('ejemploSpa', models.CharField(blank=True, max_length=300, null=True)),
                ('anioReg', models.IntegerField()),
                ('regFinal', models.BooleanField()),
                ('regUsuario', models.BooleanField(blank=True, null=True)),
                ('fk_Omc23N2', models.ForeignKey(db_column='fk_Omc23N2', on_delete=django.db.models.deletion.CASCADE, to='omniclass23.omc23nivel2', verbose_name='Nivel 2')),
            ],
            options={
                'verbose_name': 'Omc23Nivel3',
                'db_table': 'Omc23Nivel3',
            },
        ),
        migrations.CreateModel(
            name='OMC23Nivel4',
            fields=[
                ('idOmc23N4', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='idOmc23N4')),
                ('numMat', models.IntegerField(blank=True, null=True)),
                ('codigo', models.CharField(max_length=11, unique=True)),
                ('descriEng', models.CharField(max_length=100)),
                ('descriSpa', models.CharField(max_length=110)),
                ('definicionEng', models.CharField(blank=True, max_length=350, null=True)),
                ('definicionSpa', models.CharField(blank=True, max_length=400, null=True)),
                ('ejemploEng', models.CharField(blank=True, max_length=300, null=True)),
                ('ejemploSpa', models.CharField(blank=True, max_length=300, null=True)),
                ('anioReg', models.IntegerField()),
                ('regFinal', models.BooleanField()),
                ('regUsuario', models.BooleanField(blank=True, null=True)),
                ('fk_Omc23N3', models.ForeignKey(db_column='fk_Omc23N3', on_delete=django.db.models.deletion.CASCADE, to='omniclass23.omc23nivel3', verbose_name='Nivel 3')),
            ],
            options={
                'verbose_name': 'Omc23Nivel4',
                'db_table': 'Omc23Nivel4',
            },
        ),
        migrations.CreateModel(
            name='OMC23Nivel5',
            fields=[
                ('idOmc23N5', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='idOmc23N5')),
                ('numMat', models.IntegerField(blank=True, null=True)),
                ('codigo', models.CharField(max_length=13, unique=True)),
                ('descriEng', models.CharField(max_length=120)),
                ('descriSpa', models.CharField(max_length=120)),
                ('definicionEng', models.CharField(blank=True, max_length=250, null=True)),
                ('definicionSpa', models.CharField(blank=True, max_length=350, null=True)),
                ('ejemploEng', models.CharField(blank=True, max_length=150, null=True)),
                ('ejemploSpa', models.CharField(blank=True, max_length=150, null=True)),
                ('anioReg', models.IntegerField()),
                ('regFinal', models.BooleanField()),
                ('regUsuario', models.BooleanField(blank=True, null=True)),
                ('fk_Omc23N4', models.ForeignKey(db_column='fk_Omc23N4', on_delete=django.db.models.deletion.CASCADE, to='omniclass23.omc23nivel4', verbose_name='Nivel 4')),
            ],
            options={
                'verbose_name': 'Omc23Nivel5',
                'db_table': 'Omc23Nivel5',
            },
        ),
        migrations.CreateModel(
            name='OMC23Nivel6',
            fields=[
                ('idOmc23N6', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='idOmc23N6')),
                ('numMat', models.IntegerField(blank=True, null=True)),
                ('codigo', models.CharField(max_length=15, unique=True)),
                ('descriEng', models.CharField(max_length=100)),
                ('descriSpa', models.CharField(max_length=100)),
                ('definicionEng', models.CharField(blank=True, max_length=250, null=True)),
                ('definicionSpa', models.CharField(blank=True, max_length=350, null=True)),
                ('ejemploEng', models.CharField(blank=True, max_length=150, null=True)),
                ('ejemploSpa', models.CharField(blank=True, max_length=150, null=True)),
                ('anioReg', models.IntegerField()),
                ('regFinal', models.BooleanField()),
                ('regUsuario', models.BooleanField(blank=True, null=True)),
                ('fk_Omc23N5', models.ForeignKey(db_column='fk_Omc23N5', on_delete=django.db.models.deletion.CASCADE, to='omniclass23.omc23nivel5', verbose_name='Nivel 5')),
            ],
            options={
                'verbose_name': 'Omc23Nivel6',
                'db_table': 'Omc23Nivel6',
            },
        ),
    ]
