# Generated by Django 3.2.13 on 2022-11-09 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OMC41Nivel1',
            fields=[
                ('idOmc41N1', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='idOmc41N1')),
                ('codigo', models.CharField(max_length=9, unique=True)),
                ('descriEng', models.CharField(max_length=25)),
                ('descriSpa', models.CharField(blank=True, max_length=25, null=True)),
                ('definicionEng', models.CharField(max_length=150)),
                ('definicionSpa', models.CharField(max_length=150)),
                ('anioReg', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Omc41Nivel1',
                'db_table': 'Omc41Nivel1',
            },
        ),
        migrations.CreateModel(
            name='OMC41Nivel2',
            fields=[
                ('idOmc41N2', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='idOmc41N2')),
                ('codigo', models.CharField(max_length=9, unique=True)),
                ('descriEng', models.CharField(max_length=35)),
                ('descriSpa', models.CharField(max_length=35)),
                ('definicionEng', models.CharField(max_length=150)),
                ('definicionSpa', models.CharField(max_length=250)),
                ('anioReg', models.IntegerField()),
                ('fk_Omc41N1', models.ForeignKey(db_column='fk_Omc41N1', on_delete=django.db.models.deletion.CASCADE, to='omniclass41.omc41nivel1', verbose_name='Nivel 1')),
            ],
            options={
                'verbose_name': 'Omc41Nivel2',
                'db_table': 'Omc41Nivel2',
            },
        ),
        migrations.CreateModel(
            name='OMC41Nivel3',
            fields=[
                ('idOmc41N3', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='idOmc41N3')),
                ('numMat', models.IntegerField(blank=True, null=True)),
                ('codigo', models.CharField(max_length=9, unique=True)),
                ('descriEng', models.CharField(max_length=40)),
                ('descriSpa', models.CharField(max_length=45)),
                ('definicionEng', models.CharField(max_length=270)),
                ('definicionSpa', models.CharField(max_length=300)),
                ('anioReg', models.IntegerField()),
                ('regFinal', models.BooleanField()),
                ('fk_Omc41N2', models.ForeignKey(db_column='fk_Omc41N2', on_delete=django.db.models.deletion.CASCADE, to='omniclass41.omc41nivel2', verbose_name='Nivel 2')),
            ],
            options={
                'verbose_name': 'Omc41Nivel3',
                'db_table': 'Omc41Nivel3',
            },
        ),
        migrations.CreateModel(
            name='OMC41Nivel4',
            fields=[
                ('idOmc41N4', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='idOmc41N4')),
                ('numMat', models.IntegerField(blank=True, null=True)),
                ('codigo', models.CharField(max_length=11, unique=True)),
                ('descriEng', models.CharField(max_length=50)),
                ('descriSpa', models.CharField(max_length=55)),
                ('definicionEng', models.CharField(max_length=350)),
                ('definicionSpa', models.CharField(max_length=400)),
                ('anioReg', models.IntegerField()),
                ('regFinal', models.BooleanField()),
                ('fk_Omc41N3', models.ForeignKey(db_column='fk_Omc41N3', on_delete=django.db.models.deletion.CASCADE, to='omniclass41.omc41nivel3', verbose_name='Nivel 3')),
            ],
            options={
                'verbose_name': 'Omc41Nivel4',
                'db_table': 'Omc41Nivel4',
            },
        ),
        migrations.CreateModel(
            name='OMC41Nivel5',
            fields=[
                ('idOmc41N5', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='idOmc41N5')),
                ('numMat', models.IntegerField(blank=True, null=True)),
                ('codigo', models.CharField(max_length=13, unique=True)),
                ('descriEng', models.CharField(max_length=35)),
                ('descriSpa', models.CharField(max_length=45)),
                ('definicionEng', models.CharField(max_length=350)),
                ('definicionSpa', models.CharField(max_length=400)),
                ('anioReg', models.IntegerField()),
                ('regFinal', models.BooleanField()),
                ('fk_Omc41N4', models.ForeignKey(db_column='fk_Omc41N4', on_delete=django.db.models.deletion.CASCADE, to='omniclass41.omc41nivel4', verbose_name='Nivel 4')),
            ],
            options={
                'verbose_name': 'Omc41Nivel5',
                'db_table': 'Omc41Nivel5',
            },
        ),
        migrations.CreateModel(
            name='OMC41Nivel6',
            fields=[
                ('idOmc41N6', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='idOmc41N6')),
                ('numMat', models.IntegerField(blank=True, null=True)),
                ('codigo', models.CharField(max_length=15, unique=True)),
                ('descriEng', models.CharField(max_length=30)),
                ('descriSpa', models.CharField(max_length=30)),
                ('definicionEng', models.CharField(max_length=250)),
                ('definicionSpa', models.CharField(max_length=300)),
                ('anioReg', models.IntegerField()),
                ('regFinal', models.BooleanField()),
                ('fk_Omc41N5', models.ForeignKey(db_column='fk_Omc41N5', on_delete=django.db.models.deletion.CASCADE, to='omniclass41.omc41nivel5', verbose_name='Nivel 5')),
            ],
            options={
                'verbose_name': 'Omc41Nivel6',
                'db_table': 'Omc41Nivel6',
            },
        ),
    ]
