# Generated by Django 3.2.13 on 2022-11-09 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Normativa',
            fields=[
                ('idNormativa', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='idNormativa')),
                ('nombreSpa', models.CharField(blank=True, max_length=300, null=True)),
                ('nombreEng', models.CharField(max_length=250)),
                ('fk_Acronimo', models.IntegerField()),
            ],
            options={
                'db_table': 'Normativa',
            },
        ),
    ]
