# Generated by Django 3.2.13 on 2022-11-09 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UFTCategorias',
            fields=[
                ('idUftCat', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='idUftCat')),
                ('codigo', models.CharField(max_length=1)),
                ('descriEng', models.CharField(max_length=45)),
                ('descriSpa', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'UftCategorias',
            },
        ),
        migrations.CreateModel(
            name='UFTNivel2',
            fields=[
                ('idUftN2', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='idUftN2')),
                ('codigo', models.CharField(max_length=3)),
                ('descriEng', models.CharField(max_length=70)),
                ('descriSpa', models.CharField(blank=True, max_length=70, null=True)),
                ('explicacionEng', models.CharField(blank=True, max_length=70, null=True)),
                ('explicacionSpa', models.CharField(blank=True, max_length=100, null=True)),
                ('fk_UftCat', models.ForeignKey(db_column='fk_UftCat', on_delete=django.db.models.deletion.CASCADE, to='uniformat.uftcategorias', verbose_name='Categoria')),
            ],
            options={
                'db_table': 'UFTNivel2',
            },
        ),
        migrations.CreateModel(
            name='UFTNivel3',
            fields=[
                ('idUftN3', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='idUftN3')),
                ('codigo', models.CharField(max_length=10)),
                ('descriEng', models.CharField(max_length=150)),
                ('descriSpa', models.CharField(blank=True, max_length=150, null=True)),
                ('explicacionEng', models.CharField(blank=True, max_length=700, null=True)),
                ('explicacionSpa', models.CharField(blank=True, max_length=800, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=100, null=True)),
                ('fk_UftN2', models.ForeignKey(db_column='fk_UftN2', on_delete=django.db.models.deletion.CASCADE, to='uniformat.uftnivel2', verbose_name='Categoria Nivel 2')),
            ],
            options={
                'db_table': 'UFTNivel3',
            },
        ),
        migrations.CreateModel(
            name='UFTNivel4',
            fields=[
                ('idUftN4', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='idUftN4')),
                ('codigo', models.CharField(max_length=10)),
                ('descriEng', models.CharField(max_length=200)),
                ('descriSpa', models.CharField(blank=True, max_length=200, null=True)),
                ('explicacionEng', models.TextField(blank=True, null=True)),
                ('explicacionSpa', models.TextField(blank=True, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=100, null=True)),
                ('fk_UftN3', models.ForeignKey(db_column='fk_UftN3', on_delete=django.db.models.deletion.CASCADE, to='uniformat.uftnivel3', verbose_name='Categoria Nivel 3')),
            ],
            options={
                'db_table': 'UFTNivel4',
            },
        ),
        migrations.CreateModel(
            name='UFTNivel5',
            fields=[
                ('idUftN5', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='idUftN5')),
                ('codigo', models.CharField(max_length=10)),
                ('descriEng', models.CharField(max_length=100)),
                ('descriSpa', models.CharField(blank=True, max_length=150, null=True)),
                ('explicacionEng', models.CharField(blank=True, max_length=200, null=True)),
                ('explicacionSpa', models.CharField(blank=True, max_length=250, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=100, null=True)),
                ('fk_UftN4', models.ForeignKey(db_column='fk_UftN4', on_delete=django.db.models.deletion.CASCADE, to='uniformat.uftnivel4', verbose_name='Categoria Nivel 4')),
            ],
            options={
                'db_table': 'UFTNivel5',
            },
        ),
    ]
