# Generated by Django 3.2.13 on 2022-11-09 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OMC34Nivel1',
            fields=[
                ('idOmc34N1', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='idOmc34N1')),
                ('codigo', models.CharField(max_length=9, unique=True)),
                ('descriEng', models.CharField(max_length=30)),
                ('descriSpa', models.CharField(max_length=30)),
                ('definicionEng', models.CharField(max_length=200)),
                ('definicionSpa', models.CharField(max_length=200)),
                ('anioReg', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Omc34Nivel1',
                'db_table': 'Omc34Nivel1',
            },
        ),
        migrations.CreateModel(
            name='OMC34Nivel2',
            fields=[
                ('idOmc34N2', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='idOmc34N2')),
                ('codigo', models.CharField(max_length=9, unique=True)),
                ('descriEng', models.CharField(max_length=35)),
                ('descriSpa', models.CharField(max_length=50)),
                ('definicionEng', models.CharField(max_length=300)),
                ('definicionSpa', models.CharField(max_length=300)),
                ('anioReg', models.IntegerField()),
                ('regFinal', models.BooleanField()),
                ('fk_Omc34N1', models.ForeignKey(db_column='fk_Omc34N1', on_delete=django.db.models.deletion.CASCADE, related_name='children', to='omniclass34.omc34nivel1', verbose_name='Nivel 1')),
            ],
            options={
                'verbose_name': 'Omc34Nivel2',
                'db_table': 'Omc34Nivel2',
            },
        ),
        migrations.CreateModel(
            name='OMC34Nivel3',
            fields=[
                ('idOmc34N3', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='idOmc34N3')),
                ('codigo', models.CharField(max_length=9, unique=True)),
                ('descriEng', models.CharField(max_length=50)),
                ('descriSpa', models.CharField(max_length=50)),
                ('definicionEng', models.CharField(max_length=350)),
                ('definicionSpa', models.CharField(max_length=330)),
                ('anioReg', models.IntegerField()),
                ('regFinal', models.BooleanField()),
                ('regUsuario', models.BooleanField(blank=True, null=True)),
                ('fuenteInf', models.CharField(blank=True, max_length=45, null=True)),
                ('anioRegInf', models.DateField(blank=True, null=True)),
                ('fk_Omc34N2', models.ForeignKey(db_column='fk_Omc34N2', on_delete=django.db.models.deletion.CASCADE, related_name='children', to='omniclass34.omc34nivel2', verbose_name='Nivel 2')),
            ],
            options={
                'verbose_name': 'Omc34Nivel3',
                'db_table': 'Omc34Nivel3',
            },
        ),
        migrations.CreateModel(
            name='OMC34Nivel4',
            fields=[
                ('idOmc34N4', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='idOmc34N3')),
                ('codigo', models.CharField(max_length=11, unique=True)),
                ('descriEng', models.CharField(max_length=50)),
                ('descriSpa', models.CharField(max_length=65)),
                ('definicionEng', models.CharField(max_length=250)),
                ('definicionSpa', models.CharField(max_length=300)),
                ('anioReg', models.IntegerField()),
                ('regFinal', models.BooleanField()),
                ('regUsuario', models.BooleanField(blank=True, null=True)),
                ('fuenteInf', models.CharField(blank=True, max_length=45, null=True)),
                ('anioRegInf', models.DateField(blank=True, null=True)),
                ('fk_Omc34N3', models.ForeignKey(db_column='fk_Omc34N3', on_delete=django.db.models.deletion.CASCADE, related_name='children', to='omniclass34.omc34nivel3', verbose_name='Nivel 3')),
            ],
            options={
                'verbose_name': 'Omc34Nivel4',
                'db_table': 'Omc34Nivel4',
            },
        ),
        migrations.CreateModel(
            name='OMC34Nivel5',
            fields=[
                ('idOmc34N5', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='idOmc34N3')),
                ('Codigo', models.CharField(max_length=11, unique=True)),
                ('descriEng', models.CharField(max_length=50)),
                ('descriSpa', models.CharField(max_length=65)),
                ('definicionEng', models.CharField(max_length=250)),
                ('definicionSpa', models.CharField(max_length=300)),
                ('anioReg', models.IntegerField()),
                ('regFinal', models.BooleanField()),
                ('regUsuario', models.BooleanField()),
                ('fuenteInf', models.CharField(blank=True, max_length=45, null=True)),
                ('anioRegInf', models.DateField(blank=True, null=True)),
                ('fk_Omc34N4', models.ForeignKey(db_column='fk_Omc34N4', on_delete=django.db.models.deletion.CASCADE, related_name='children', to='omniclass34.omc34nivel4', verbose_name='Nivel 4')),
            ],
            options={
                'verbose_name': 'Omc34Nivel5',
                'db_table': 'Omc34Nivel5',
            },
        ),
    ]
