# Generated by Django 3.2.13 on 2022-11-09 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RolesOrg',
            fields=[
                ('idRolOrg', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='idRolOrg')),
                ('cveMo', models.IntegerField(blank=True, null=True)),
                ('codigo', models.CharField(max_length=11)),
                ('consecutivo', models.CharField(max_length=5)),
                ('descriEng', models.CharField(blank=True, max_length=65, null=True)),
                ('descriSpa', models.CharField(max_length=75)),
                ('definicionEng', models.CharField(blank=True, max_length=150, null=True)),
                ('definicionSpa', models.CharField(max_length=200)),
                ('fuenteInf', models.CharField(max_length=45)),
                ('fecRegInf', models.DateField()),
            ],
            options={
                'db_table': 'RolesOrg',
            },
        ),
    ]
