# Generated by Django 3.2.13 on 2022-11-09 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datosgeograficos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('idMarca', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='idMarca')),
                ('nombre', models.CharField(max_length=45, unique=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Marca',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('idProveedor', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='idProveedor')),
                ('nombre', models.CharField(max_length=60)),
                ('RFC', models.CharField(blank=True, max_length=13, null=True)),
                ('email', models.CharField(blank=True, max_length=45, null=True)),
                ('fabricante', models.BooleanField(blank=True, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=500, null=True)),
                ('logoImg', models.ImageField(blank=True, max_length=255, null=True, upload_to='proveedor/', verbose_name='Logo')),
                ('urlSitioWeb', models.CharField(blank=True, max_length=70, null=True)),
            ],
            options={
                'db_table': 'Proveedor',
            },
        ),
        migrations.CreateModel(
            name='SectorMercado',
            fields=[
                ('idSecMer', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='idSecMer')),
                ('nombre', models.CharField(max_length=40, unique=True)),
            ],
            options={
                'db_table': 'SectorMercado',
            },
        ),
        migrations.CreateModel(
            name='SucursalProv',
            fields=[
                ('idSucProv', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='idSucProv')),
                ('alias', models.CharField(max_length=80)),
                ('numTel', models.CharField(max_length=20)),
                ('contactoAten', models.CharField(max_length=50)),
                ('nomSuperior', models.CharField(blank=True, max_length=50, null=True)),
                ('cargoSuperior', models.CharField(blank=True, max_length=50, null=True)),
                ('calle', models.CharField(max_length=50)),
                ('noInt', models.IntegerField()),
                ('noExt', models.IntegerField(blank=True, null=True)),
                ('colonia', models.CharField(max_length=50)),
                ('fk_CP', models.ForeignKey(db_column='fk_CP', on_delete=django.db.models.deletion.CASCADE, to='datosgeograficos.cp', verbose_name='CP')),
                ('fk_Proveedor', models.ForeignKey(db_column='fk_Proveedor', on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedor', verbose_name='Proveedor')),
            ],
            options={
                'db_table': 'SucursalProv',
            },
        ),
        migrations.CreateModel(
            name='SectorProv',
            fields=[
                ('idSecProv', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='idSecProv')),
                ('fk_Proveedor', models.ForeignKey(db_column='fk_Proveedor', on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedor', verbose_name='Proveedor')),
                ('fk_SecMer', models.ForeignKey(db_column='fk_SecMer', on_delete=django.db.models.deletion.CASCADE, to='proveedores.sectormercado', verbose_name='Sector Mercado')),
            ],
            options={
                'db_table': 'SectorProv',
            },
        ),
        migrations.CreateModel(
            name='ProveedorMarca',
            fields=[
                ('idProvMar', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='idProveedorMarca')),
                ('fk_Marca', models.ForeignKey(db_column='fk_Marca', on_delete=django.db.models.deletion.CASCADE, to='proveedores.marca', verbose_name='Marca')),
                ('fk_Proveedor', models.ForeignKey(db_column='fk_Proveedor', on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedor', verbose_name='Proveedor')),
            ],
            options={
                'db_table': 'ProveedorMarca',
            },
        ),
        migrations.CreateModel(
            name='MaterialProveedor',
            fields=[
                ('idMatProv', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='idMatProv')),
                ('precio', models.FloatField()),
                ('fechaAct', models.DateTimeField()),
                ('fuenteInfo', models.CharField(blank=True, max_length=100, null=True)),
                ('fk_Material', models.IntegerField()),
                ('fk_ProvMar', models.ForeignKey(blank=True, db_column='fk_ProvMar', null=True, on_delete=django.db.models.deletion.SET_NULL, to='proveedores.proveedormarca')),
                ('fk_SucProv', models.ForeignKey(db_column='fk_SucProv', on_delete=django.db.models.deletion.CASCADE, to='proveedores.sucursalprov', verbose_name='Sucursal')),
            ],
            options={
                'db_table': 'MaterialProveedor',
            },
        ),
    ]
