# Generated by Django 3.2.13 on 2022-11-09 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OMC35Nivel1',
            fields=[
                ('idOmc35N1', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='idOmc35N1')),
                ('codigo', models.CharField(max_length=9, unique=True)),
                ('descriEng', models.CharField(max_length=30)),
                ('descriSpa', models.CharField(max_length=100)),
                ('definicionEng', models.CharField(blank=True, max_length=150, null=True)),
                ('definicionSpa', models.CharField(blank=True, max_length=150, null=True)),
                ('anioReg', models.IntegerField()),
                ('fk_EnvOMC', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Omc35Nivel1',
                'db_table': 'Omc35Nivel1',
            },
        ),
        migrations.CreateModel(
            name='OMC35Nivel2',
            fields=[
                ('idOmc35N2', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='idOmc35N1')),
                ('codigo', models.CharField(max_length=9, unique=True)),
                ('descriEng', models.CharField(max_length=50)),
                ('descriSpa', models.CharField(max_length=80)),
                ('definicionEng', models.CharField(blank=True, max_length=150, null=True)),
                ('definicionSpa', models.CharField(blank=True, max_length=150, null=True)),
                ('anioReg', models.IntegerField()),
                ('fk_Omc35N1', models.ForeignKey(db_column='fk_Omc35N1', on_delete=django.db.models.deletion.CASCADE, to='omniclass35.omc35nivel1', verbose_name='Nivel 1')),
            ],
            options={
                'verbose_name': 'Omc35Nivel2',
                'db_table': 'Omc35Nivel2',
            },
        ),
        migrations.CreateModel(
            name='OMC35Nivel3',
            fields=[
                ('idOmc35N3', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='idOmc35N3')),
                ('cveHe', models.IntegerField(blank=True, null=True)),
                ('codigo', models.CharField(max_length=9, unique=True)),
                ('descriEng', models.CharField(max_length=60)),
                ('descriSpa', models.CharField(max_length=80)),
                ('definicionEng', models.CharField(blank=True, max_length=150, null=True)),
                ('definicionSpa', models.CharField(blank=True, max_length=150, null=True)),
                ('anioReg', models.IntegerField()),
                ('regFinal', models.BooleanField()),
                ('fk_Omc35N2', models.ForeignKey(db_column='fk_Omc35N2', on_delete=django.db.models.deletion.CASCADE, to='omniclass35.omc35nivel2', verbose_name='Nivel 2')),
            ],
            options={
                'verbose_name': 'Omc35Nivel3',
                'db_table': 'Omc35Nivel3',
            },
        ),
        migrations.CreateModel(
            name='OMC35Nivel4',
            fields=[
                ('idOmc35N4', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='idOmc35N4')),
                ('cveHe', models.IntegerField(blank=True, null=True)),
                ('codigo', models.CharField(max_length=11, unique=True)),
                ('descriEng', models.CharField(max_length=80)),
                ('descriSpa', models.CharField(max_length=90)),
                ('definicionEng', models.CharField(blank=True, max_length=150, null=True)),
                ('definicionSpa', models.CharField(blank=True, max_length=150, null=True)),
                ('anioReg', models.IntegerField()),
                ('regFinal', models.BooleanField()),
                ('fk_Omc35N3', models.ForeignKey(db_column='fk_Omc35N3', on_delete=django.db.models.deletion.CASCADE, to='omniclass35.omc35nivel3', verbose_name='Nivel 3')),
            ],
            options={
                'verbose_name': 'Omc35Nivel4',
                'db_table': 'Omc35Nivel4',
            },
        ),
        migrations.CreateModel(
            name='OMC35Nivel5',
            fields=[
                ('idOmc35N5', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='idOmc35N5')),
                ('cveHe', models.IntegerField(blank=True, null=True)),
                ('codigo', models.CharField(max_length=13, unique=True)),
                ('descriEng', models.CharField(max_length=90)),
                ('descriSpa', models.CharField(max_length=100)),
                ('definicionEng', models.CharField(blank=True, max_length=150, null=True)),
                ('definicionSpa', models.CharField(blank=True, max_length=150, null=True)),
                ('anioReg', models.IntegerField()),
                ('regFinal', models.BooleanField()),
                ('fk_Omc35N4', models.ForeignKey(db_column='fk_Omc35N4', on_delete=django.db.models.deletion.CASCADE, to='omniclass35.omc35nivel4', verbose_name='Nivel 4')),
            ],
            options={
                'verbose_name': 'Omc35Nivel5',
                'db_table': 'Omc35Nivel5',
            },
        ),
        migrations.CreateModel(
            name='OMC35Nivel6',
            fields=[
                ('idOmc35N6', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='idOmc35N6')),
                ('cveHe', models.IntegerField(blank=True, null=True)),
                ('codigo', models.CharField(max_length=15, unique=True)),
                ('descriEng', models.CharField(max_length=75)),
                ('descriSpa', models.CharField(max_length=100)),
                ('definicionEng', models.CharField(blank=True, max_length=150, null=True)),
                ('definicionSpa', models.CharField(blank=True, max_length=150, null=True)),
                ('anioReg', models.IntegerField()),
                ('regFinal', models.BooleanField()),
                ('fk_Omc35N5', models.ForeignKey(db_column='fk_Omc35N5', on_delete=django.db.models.deletion.CASCADE, to='omniclass35.omc35nivel5', verbose_name='Nivel 5')),
            ],
            options={
                'verbose_name': 'Omc35Nivel6',
                'db_table': 'Omc35Nivel6',
            },
        ),
    ]
