# Generated by Django 3.2.13 on 2022-11-09 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubTipUni',
            fields=[
                ('idStu', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='idStu')),
                ('subtipo', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'subtipUni',
            },
        ),
        migrations.CreateModel(
            name='TipoUniMed',
            fields=[
                ('idTum', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='idTum')),
                ('tipo', models.CharField(max_length=65)),
            ],
            options={
                'db_table': 'TipoUniMed',
            },
        ),
        migrations.CreateModel(
            name='UnidadesMedida',
            fields=[
                ('idUniMed', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='idUniMed')),
                ('cveSat', models.CharField(blank=True, max_length=3, null=True)),
                ('unidad', models.CharField(max_length=15, unique=True)),
                ('descripcion', models.CharField(max_length=80)),
                ('sistema', models.CharField(blank=True, max_length=30, null=True)),
                ('fk_Stu', models.ForeignKey(db_column='fk_Stu', on_delete=django.db.models.deletion.CASCADE, to='unidadesmedida.subtipuni', verbose_name='Subtipo Unidad de Medida')),
            ],
            options={
                'db_table': 'UnidadesMedida',
            },
        ),
        migrations.AddField(
            model_name='subtipuni',
            name='fk_Tum',
            field=models.ForeignKey(db_column='fk_Tum', on_delete=django.db.models.deletion.CASCADE, to='unidadesmedida.tipounimed', verbose_name='Tipo Unidad de Medida'),
        ),
    ]
